### ISSUE TITLE
invalid response (without details exception cause)

### ISSUE THREAD

**Issue by GennadyMV** [i-novus-llc/n2o-platform#17]
Hi
 i have app based on 
 
    <parent>
        <groupId>net.n2oapp.platform</groupId>
        <artifactId>n2o-boot-platform-parent</artifactId>
        <version>4.4.0</version>
        <relativePath />
    </parent>
 
 when  app throws java.lang.NullPointerException, I see it in my logs
 
 but response what i have is:
   
 Headers: {exception-class=net.n2oapp.platform.jaxrs.RestException, Date=Wed, 29 Jun 2022 06:09:00 GMT, Content-Type=application/json;charset=UTF-8}
    Payload: {"message":"87495 09 6635"}
    
    how can i get real response from app with stacktrace?

**Comment by keddok** [comment]
Sorry for late answer.
We decided that the real stacktrace on frontend is a security issue. That is why response wrapped with some simple human readable code like 87495 09 6635. This code is supposed to be passed on to the support team. Then support team can find real exception with stacktrace in app logs.
